// <auto-generated />
using System;
using BatchAssessment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BatchAssessment.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211124202828_addBatchtoDb")]
    partial class addBatchtoDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BatchAssessment.Models.ACL", b =>
                {
                    b.Property<string>("ReadUser")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("BatchModelBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReadGroup")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReadUser");

                    b.HasIndex("BatchModelBatchId");

                    b.ToTable("ACLs");
                });

            modelBuilder.Entity("BatchAssessment.Models.Atribute", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("BatchModelBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.HasIndex("BatchModelBatchId");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("BatchAssessment.Models.BatchModel", b =>
                {
                    b.Property<Guid>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BatchId");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("BatchAssessment.Models.ACL", b =>
                {
                    b.HasOne("BatchAssessment.Models.BatchModel", null)
                        .WithMany("ACLs")
                        .HasForeignKey("BatchModelBatchId");
                });

            modelBuilder.Entity("BatchAssessment.Models.Atribute", b =>
                {
                    b.HasOne("BatchAssessment.Models.BatchModel", null)
                        .WithMany("Attributes")
                        .HasForeignKey("BatchModelBatchId");
                });
#pragma warning restore 612, 618
        }
    }
}
